before_script:
    - apt-get -q update && apt-get -yq install make gcc
    - gcc --version
    - make --version

server:
    script:
        - make
        - cd tester && ./test_script.sh ../server 8080
        - cd ..
